var hierarchy =
[
    [ "account", "classaccount.html", null ],
    [ "AuditLog", "class_audit_log.html", null ],
    [ "Command", "class_command.html", [
      [ "AccountBanCommand", "class_account_ban_command.html", null ],
      [ "AccountInfoCommand", "class_account_info_command.html", null ],
      [ "AccountUnbanCommand", "class_account_unban_command.html", null ],
      [ "AccountVerifyCommand", "class_account_verify_command.html", null ],
      [ "CreateDBCommand", "class_create_d_b_command.html", null ],
      [ "DEBUG_removeDBCommand", "class_d_e_b_u_g__remove_d_b_command.html", null ],
      [ "DEBUG_setAccountCurrencyCommand", "class_d_e_b_u_g__set_account_currency_command.html", null ],
      [ "DebugOnCommand", "class_debug_on_command.html", null ],
      [ "NewAccountCommand", "class_new_account_command.html", null ],
      [ "PrintAccountListCommand", "class_print_account_list_command.html", null ],
      [ "PrintUserListCommand", "class_print_user_list_command.html", null ],
      [ "RegisterUserCommand", "class_register_user_command.html", null ],
      [ "SetAccountCommand", "class_set_account_command.html", null ],
      [ "TransactionRequestListCommand", "class_transaction_request_list_command.html", null ],
      [ "TransactionRequestPANCommand", "class_transaction_request_p_a_n_command.html", null ],
      [ "UnitTestCommand", "class_unit_test_command.html", null ],
      [ "UserInfoCommand", "class_user_info_command.html", null ],
      [ "getSessionIdCommand", "classget_session_id_command.html", null ],
      [ "getUserAccountsCommand", "classget_user_accounts_command.html", null ],
      [ "userLoginCommand", "classuser_login_command.html", null ],
      [ "userLogoutCommand", "classuser_logout_command.html", null ]
    ] ],
    [ "CommandsManager", "class_commands_manager.html", null ],
    [ "fronted_User", "structfronted___user.html", null ],
    [ "handleInfo", "structhandle_info.html", null ],
    [ "Log", "class_log.html", null ],
    [ "LogEntry", "struct_log_entry.html", null ],
    [ "LogEye", "class_log_eye.html", null ],
    [ "Logger", "class_logger.html", null ],
    [ "mainProcess", "classmain_process.html", null ],
    [ "passportData", "structpassport_data.html", null ],
    [ "Response", "class_response.html", [
      [ "AccountBanResponse", "struct_account_ban_response.html", null ],
      [ "AccountInfoResponse", "class_account_info_response.html", null ],
      [ "AccountListResponse", "class_account_list_response.html", null ],
      [ "AccountUnbanResponse", "struct_account_unban_response.html", null ],
      [ "AccountVerifyResponse", "class_account_verify_response.html", null ],
      [ "CreateDBResponse", "class_create_d_b_response.html", null ],
      [ "DEBUG_removeDBResponse", "class_d_e_b_u_g__remove_d_b_response.html", null ],
      [ "DEBUG_setAccountCurrencyResponse", "class_d_e_b_u_g__set_account_currency_response.html", null ],
      [ "DebugOnResponse", "class_debug_on_response.html", null ],
      [ "GetSessionIdResponse", "class_get_session_id_response.html", null ],
      [ "LoginResponse", "class_login_response.html", null ],
      [ "LogoutResponse", "class_logout_response.html", null ],
      [ "MeResponse", "class_me_response.html", null ],
      [ "NewAccountResponse", "class_new_account_response.html", null ],
      [ "NewUserResponse", "class_new_user_response.html", null ],
      [ "SetAccountResponse", "class_set_account_response.html", null ],
      [ "TransactionRequestListResponse", "class_transaction_request_list_response.html", null ],
      [ "TransactionRequestPANResponse", "class_transaction_request_p_a_n_response.html", null ],
      [ "UnitTestResponse", "class_unit_test_response.html", null ],
      [ "UserInfoResponse", "class_user_info_response.html", null ],
      [ "UserListResponse", "class_user_list_response.html", null ],
      [ "getUserAccountsResponse", "structget_user_accounts_response.html", null ]
    ] ],
    [ "ResponseManager", "class_response_manager.html", null ],
    [ "Session", "struct_session.html", null ],
    [ "sessionConstruct", "structsession_construct.html", null ],
    [ "TransactionLog", "class_transaction_log.html", null ],
    [ "User", "class_user.html", null ]
];