/********************************************************************************
** Form generated from reading UI file 'Window.ui'
**
** Created by: Qt User Interface Compiler version 6.10.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_WINDOW_H
#define UI_WINDOW_H

#include <QtCore/QVariant>
#include <QtGui/QIcon>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QCommandLinkButton>
#include <QtWidgets/QDialog>
#include <QtWidgets/QDoubleSpinBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QScrollArea>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *loginWidget;
    QLabel *logo_main;
    QPushButton *LoginButton;
    QCommandLinkButton *ForgedPasswodButton;
    QLabel *login_label;
    QLineEdit *login_line_edit;
    QLabel *label;
    QLabel *label_unput_password;
    QCommandLinkButton *RegisterButton;
    QLabel *label_login;
    QLineEdit *password_line_edit;
    QFrame *SessionInfoFrame;
    QLabel *user_id_value;
    QLabel *user_id_label;
    QLabel *session_id_label;
    QLabel *session_id_value;
    QWidget *RegWidget;
    QPushButton *RegisterButtonCompl;
    QLabel *logo_main_2;
    QLineEdit *NameEdit;
    QLineEdit *SurnameEdit;
    QLabel *ProjectNameLabel;
    QLabel *RegLabel1;
    QLabel *NameLabel;
    QLabel *SurnameLabel;
    QLabel *LoginLabel;
    QLineEdit *LoginEdit;
    QLabel *label_2;
    QLineEdit *PasswordEdit;
    QPushButton *BackToLoginButton;
    QWidget *MainMenuWidget;
    QWidget *mainMenuWidget;
    QPushButton *TransactionIBAN;
    QPushButton *TransactionPAN;
    QPushButton *TransactionOther;
    QPushButton *LogoutButton;
    QPushButton *updateButton;
    QWidget *supportInfoWidget;
    QLabel *user_id_value_3;
    QLabel *user_id_label_3;
    QLabel *session_id_value_3;
    QLabel *session_id_label_3;
    QTabWidget *main;
    QWidget *AccountsTab;
    QScrollArea *CardsScroll;
    QWidget *CardsScrollAreaWidgetContent;
    QWidget *Card_Template;
    QLabel *Card_image;
    QLabel *Card_Value;
    QLabel *Card_Value_Type;
    QLabel *Card_PAN;
    QLabel *Card_BankName;
    QWidget *cardInfoWidget;
    QLabel *Card_Name;
    QLabel *Card_Status;
    QLabel *Card_MGPM;
    QLabel *Card_expiration_date;
    QLabel *Card_Iban;
    QWidget *HistoryTab_2;
    QScrollArea *historyScrollArea;
    QWidget *HistoryScrollAreaWidgetContents;
    QWidget *TransactionTemplateWidget;
    QLabel *History_IMG_logo;
    QLabel *History_ammount;
    QLabel *History_value_type;
    QLabel *History_PAN_from;
    QLabel *History_PAN_to;
    QFrame *filterWidget_2;
    QCheckBox *incomeCheckBox_2;
    QCheckBox *expensesCheckBox_2;
    QComboBox *cardsCheckBox_2;
    QLabel *label_6;
    QPushButton *load_more_button_2;
    QWidget *DepositeTab_2;
    QScrollArea *CardsScroll_4;
    QWidget *scrollAreaWidgetContents_6;
    QWidget *Card_Dep1_2;
    QWidget *OtherTab_2;
    QLabel *msg_box;
    QWidget *TransactionWidget;
    QFrame *MainTransactionFrame;
    QComboBox *UserCardsBox;
    QLabel *TransactionFrameName;
    QLabel *Transaction_From;
    QLabel *Transaction_To;
    QLineEdit *PAN_to;
    QDoubleSpinBox *AmountSpin;
    QLabel *AmountLabel;
    QPushButton *TransactionRequestButton;
    QLineEdit *PIN_Edit;
    QLabel *label_3;
    QPushButton *BackFromTransactionWindow;

    void setupUi(QDialog *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName("MainWindow");
        MainWindow->setEnabled(true);
        MainWindow->resize(1250, 713);
        QSizePolicy sizePolicy(QSizePolicy::Policy::Preferred, QSizePolicy::Policy::Ignored);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(MainWindow->sizePolicy().hasHeightForWidth());
        MainWindow->setSizePolicy(sizePolicy);
        MainWindow->setMinimumSize(QSize(620, 315));
        MainWindow->setMaximumSize(QSize(6180, 3150));
        QFont font;
        font.setPointSize(8);
        MainWindow->setFont(font);
        MainWindow->setContextMenuPolicy(Qt::NoContextMenu);
        MainWindow->setAcceptDrops(false);
        QIcon icon;
        icon.addFile(QString::fromUtf8("C:/Users/Admin/OneDrive/Pictures/GlassCubeRed1.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        MainWindow->setWindowIcon(icon);
        MainWindow->setWindowOpacity(2.000000000000000);
        loginWidget = new QWidget(MainWindow);
        loginWidget->setObjectName("loginWidget");
        loginWidget->setGeometry(QRect(0, 0, 611, 311));
        logo_main = new QLabel(loginWidget);
        logo_main->setObjectName("logo_main");
        logo_main->setGeometry(QRect(-100, -50, 561, 321));
        logo_main->setPixmap(QPixmap(QString::fromUtf8("C:/Users/Admin/OneDrive/Pictures/GlassCubeRed.png")));
        logo_main->setScaledContents(true);
        logo_main->setWordWrap(false);
        LoginButton = new QPushButton(loginWidget);
        LoginButton->setObjectName("LoginButton");
        LoginButton->setGeometry(QRect(440, 265, 93, 28));
        ForgedPasswodButton = new QCommandLinkButton(loginWidget);
        ForgedPasswodButton->setObjectName("ForgedPasswodButton");
        ForgedPasswodButton->setGeometry(QRect(420, 184, 151, 31));
        QFont font1;
        font1.setFamilies({QString::fromUtf8("Segoe UI")});
        font1.setPointSize(8);
        ForgedPasswodButton->setFont(font1);
        ForgedPasswodButton->setLayoutDirection(Qt::LeftToRight);
        ForgedPasswodButton->setIconSize(QSize(0, 0));
        login_label = new QLabel(loginWidget);
        login_label->setObjectName("login_label");
        login_label->setEnabled(true);
        login_label->setGeometry(QRect(352, 24, 231, 41));
        QFont font2;
        font2.setFamilies({QString::fromUtf8("MS Reference Sans Serif")});
        font2.setPointSize(10);
        font2.setBold(true);
        font2.setStrikeOut(false);
        font2.setKerning(true);
        font2.setStyleStrategy(QFont::PreferDefault);
        login_label->setFont(font2);
        login_label->setFocusPolicy(Qt::NoFocus);
        login_label->setAcceptDrops(false);
        login_label->setLayoutDirection(Qt::LeftToRight);
        login_label->setScaledContents(false);
        login_label->setWordWrap(false);
        login_line_edit = new QLineEdit(loginWidget);
        login_line_edit->setObjectName("login_line_edit");
        login_line_edit->setGeometry(QRect(430, 135, 161, 21));
        login_line_edit->setMaxLength(34);
        label = new QLabel(loginWidget);
        label->setObjectName("label");
        label->setEnabled(true);
        label->setGeometry(QRect(352, 1, 231, 41));
        QFont font3;
        font3.setFamilies({QString::fromUtf8("MS Reference Sans Serif")});
        font3.setPointSize(12);
        font3.setBold(true);
        font3.setStrikeOut(false);
        font3.setKerning(true);
        font3.setStyleStrategy(QFont::PreferDefault);
        label->setFont(font3);
        label->setFocusPolicy(Qt::NoFocus);
        label->setAcceptDrops(false);
        label->setLayoutDirection(Qt::LeftToRight);
        label->setScaledContents(false);
        label->setWordWrap(false);
        label_unput_password = new QLabel(loginWidget);
        label_unput_password->setObjectName("label_unput_password");
        label_unput_password->setGeometry(QRect(370, 165, 61, 16));
        RegisterButton = new QCommandLinkButton(loginWidget);
        RegisterButton->setObjectName("RegisterButton");
        RegisterButton->setGeometry(QRect(440, 215, 111, 31));
        RegisterButton->setFont(font1);
        RegisterButton->setLayoutDirection(Qt::LeftToRight);
        RegisterButton->setIconSize(QSize(0, 0));
        label_login = new QLabel(loginWidget);
        label_login->setObjectName("label_login");
        label_login->setGeometry(QRect(370, 135, 55, 16));
        password_line_edit = new QLineEdit(loginWidget);
        password_line_edit->setObjectName("password_line_edit");
        password_line_edit->setGeometry(QRect(430, 164, 161, 21));
        password_line_edit->setMaxLength(34);
        SessionInfoFrame = new QFrame(MainWindow);
        SessionInfoFrame->setObjectName("SessionInfoFrame");
        SessionInfoFrame->setEnabled(true);
        SessionInfoFrame->setGeometry(QRect(0, 280, 81, 31));
        SessionInfoFrame->setFrameShape(QFrame::StyledPanel);
        SessionInfoFrame->setFrameShadow(QFrame::Raised);
        user_id_value = new QLabel(SessionInfoFrame);
        user_id_value->setObjectName("user_id_value");
        user_id_value->setGeometry(QRect(30, 0, 42, 16));
        user_id_label = new QLabel(SessionInfoFrame);
        user_id_label->setObjectName("user_id_label");
        user_id_label->setGeometry(QRect(0, 0, 27, 16));
        session_id_label = new QLabel(SessionInfoFrame);
        session_id_label->setObjectName("session_id_label");
        session_id_label->setGeometry(QRect(0, 15, 26, 16));
        session_id_value = new QLabel(SessionInfoFrame);
        session_id_value->setObjectName("session_id_value");
        session_id_value->setGeometry(QRect(30, 15, 42, 16));
        RegWidget = new QWidget(MainWindow);
        RegWidget->setObjectName("RegWidget");
        RegWidget->setGeometry(QRect(0, 320, 611, 311));
        RegisterButtonCompl = new QPushButton(RegWidget);
        RegisterButtonCompl->setObjectName("RegisterButtonCompl");
        RegisterButtonCompl->setGeometry(QRect(450, 260, 93, 28));
        logo_main_2 = new QLabel(RegWidget);
        logo_main_2->setObjectName("logo_main_2");
        logo_main_2->setGeometry(QRect(-90, -40, 561, 321));
        logo_main_2->setPixmap(QPixmap(QString::fromUtf8("C:/Users/Admin/OneDrive/Pictures/GlassCubeRed.png")));
        logo_main_2->setScaledContents(true);
        logo_main_2->setWordWrap(false);
        NameEdit = new QLineEdit(RegWidget);
        NameEdit->setObjectName("NameEdit");
        NameEdit->setGeometry(QRect(370, 100, 101, 22));
        SurnameEdit = new QLineEdit(RegWidget);
        SurnameEdit->setObjectName("SurnameEdit");
        SurnameEdit->setGeometry(QRect(480, 100, 101, 22));
        ProjectNameLabel = new QLabel(RegWidget);
        ProjectNameLabel->setObjectName("ProjectNameLabel");
        ProjectNameLabel->setEnabled(true);
        ProjectNameLabel->setGeometry(QRect(360, 10, 231, 41));
        ProjectNameLabel->setFont(font3);
        ProjectNameLabel->setFocusPolicy(Qt::NoFocus);
        ProjectNameLabel->setAcceptDrops(false);
        ProjectNameLabel->setLayoutDirection(Qt::LeftToRight);
        ProjectNameLabel->setScaledContents(false);
        ProjectNameLabel->setWordWrap(false);
        RegLabel1 = new QLabel(RegWidget);
        RegLabel1->setObjectName("RegLabel1");
        RegLabel1->setEnabled(true);
        RegLabel1->setGeometry(QRect(360, 33, 231, 41));
        RegLabel1->setFont(font2);
        RegLabel1->setFocusPolicy(Qt::NoFocus);
        RegLabel1->setAcceptDrops(false);
        RegLabel1->setLayoutDirection(Qt::LeftToRight);
        RegLabel1->setScaledContents(false);
        RegLabel1->setWordWrap(false);
        NameLabel = new QLabel(RegWidget);
        NameLabel->setObjectName("NameLabel");
        NameLabel->setGeometry(QRect(370, 80, 55, 16));
        SurnameLabel = new QLabel(RegWidget);
        SurnameLabel->setObjectName("SurnameLabel");
        SurnameLabel->setGeometry(QRect(486, 80, 61, 16));
        LoginLabel = new QLabel(RegWidget);
        LoginLabel->setObjectName("LoginLabel");
        LoginLabel->setGeometry(QRect(370, 130, 55, 16));
        LoginEdit = new QLineEdit(RegWidget);
        LoginEdit->setObjectName("LoginEdit");
        LoginEdit->setGeometry(QRect(370, 150, 113, 22));
        label_2 = new QLabel(RegWidget);
        label_2->setObjectName("label_2");
        label_2->setGeometry(QRect(370, 180, 55, 16));
        PasswordEdit = new QLineEdit(RegWidget);
        PasswordEdit->setObjectName("PasswordEdit");
        PasswordEdit->setGeometry(QRect(370, 200, 113, 22));
        BackToLoginButton = new QPushButton(RegWidget);
        BackToLoginButton->setObjectName("BackToLoginButton");
        BackToLoginButton->setGeometry(QRect(10, 10, 93, 28));
        logo_main_2->raise();
        RegisterButtonCompl->raise();
        NameEdit->raise();
        SurnameEdit->raise();
        ProjectNameLabel->raise();
        RegLabel1->raise();
        NameLabel->raise();
        SurnameLabel->raise();
        LoginLabel->raise();
        LoginEdit->raise();
        label_2->raise();
        PasswordEdit->raise();
        BackToLoginButton->raise();
        MainMenuWidget = new QWidget(MainWindow);
        MainMenuWidget->setObjectName("MainMenuWidget");
        MainMenuWidget->setGeometry(QRect(620, 0, 611, 311));
        mainMenuWidget = new QWidget(MainMenuWidget);
        mainMenuWidget->setObjectName("mainMenuWidget");
        mainMenuWidget->setGeometry(QRect(0, 270, 611, 41));
        TransactionIBAN = new QPushButton(mainMenuWidget);
        TransactionIBAN->setObjectName("TransactionIBAN");
        TransactionIBAN->setGeometry(QRect(10, 10, 111, 28));
        TransactionPAN = new QPushButton(mainMenuWidget);
        TransactionPAN->setObjectName("TransactionPAN");
        TransactionPAN->setGeometry(QRect(130, 10, 121, 28));
        TransactionOther = new QPushButton(mainMenuWidget);
        TransactionOther->setObjectName("TransactionOther");
        TransactionOther->setEnabled(false);
        TransactionOther->setGeometry(QRect(260, 10, 141, 28));
        LogoutButton = new QPushButton(mainMenuWidget);
        LogoutButton->setObjectName("LogoutButton");
        LogoutButton->setGeometry(QRect(510, 10, 93, 28));
        updateButton = new QPushButton(mainMenuWidget);
        updateButton->setObjectName("updateButton");
        updateButton->setEnabled(true);
        updateButton->setGeometry(QRect(440, 10, 61, 28));
        supportInfoWidget = new QWidget(MainMenuWidget);
        supportInfoWidget->setObjectName("supportInfoWidget");
        supportInfoWidget->setGeometry(QRect(430, 0, 181, 21));
        user_id_value_3 = new QLabel(supportInfoWidget);
        user_id_value_3->setObjectName("user_id_value_3");
        user_id_value_3->setGeometry(QRect(30, 0, 42, 16));
        user_id_label_3 = new QLabel(supportInfoWidget);
        user_id_label_3->setObjectName("user_id_label_3");
        user_id_label_3->setGeometry(QRect(0, 0, 27, 16));
        session_id_value_3 = new QLabel(supportInfoWidget);
        session_id_value_3->setObjectName("session_id_value_3");
        session_id_value_3->setGeometry(QRect(130, 0, 42, 16));
        session_id_label_3 = new QLabel(supportInfoWidget);
        session_id_label_3->setObjectName("session_id_label_3");
        session_id_label_3->setGeometry(QRect(100, 0, 26, 16));
        main = new QTabWidget(MainMenuWidget);
        main->setObjectName("main");
        main->setEnabled(true);
        main->setGeometry(QRect(0, 0, 621, 271));
        main->setLayoutDirection(Qt::LeftToRight);
        main->setTabPosition(QTabWidget::North);
        main->setUsesScrollButtons(false);
        main->setDocumentMode(false);
        main->setTabsClosable(false);
        AccountsTab = new QWidget();
        AccountsTab->setObjectName("AccountsTab");
        CardsScroll = new QScrollArea(AccountsTab);
        CardsScroll->setObjectName("CardsScroll");
        CardsScroll->setGeometry(QRect(10, 10, 361, 211));
        CardsScroll->setFrameShape(QFrame::NoFrame);
        CardsScroll->setFrameShadow(QFrame::Sunken);
        CardsScroll->setLineWidth(0);
        CardsScroll->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        CardsScroll->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        CardsScroll->setSizeAdjustPolicy(QAbstractScrollArea::AdjustToContentsOnFirstShow);
        CardsScroll->setWidgetResizable(true);
        CardsScrollAreaWidgetContent = new QWidget();
        CardsScrollAreaWidgetContent->setObjectName("CardsScrollAreaWidgetContent");
        CardsScrollAreaWidgetContent->setGeometry(QRect(0, 0, 361, 211));
        Card_Template = new QWidget(CardsScrollAreaWidgetContent);
        Card_Template->setObjectName("Card_Template");
        Card_Template->setEnabled(true);
        Card_Template->setGeometry(QRect(0, 0, 361, 201));
        Card_Template->setMinimumSize(QSize(361, 201));
        Card_image = new QLabel(Card_Template);
        Card_image->setObjectName("Card_image");
        Card_image->setGeometry(QRect(40, 0, 274, 161));
        Card_image->setMinimumSize(QSize(271, 161));
        Card_image->setPixmap(QPixmap(QString::fromUtf8("UI/resources/images/Untitled17_20251029201549.png")));
        Card_image->setScaledContents(true);
        Card_image->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignTop);
        Card_Value = new QLabel(Card_Template);
        Card_Value->setObjectName("Card_Value");
        Card_Value->setGeometry(QRect(60, 160, 91, 31));
        Card_Value_Type = new QLabel(Card_Template);
        Card_Value_Type->setObjectName("Card_Value_Type");
        Card_Value_Type->setGeometry(QRect(180, 160, 91, 31));
        Card_PAN = new QLabel(Card_Template);
        Card_PAN->setObjectName("Card_PAN");
        Card_PAN->setGeometry(QRect(74, 90, 201, 31));
        QFont font4;
        font4.setPointSize(12);
        Card_PAN->setFont(font4);
        Card_PAN->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        Card_PAN->setAlignment(Qt::AlignCenter);
        Card_BankName = new QLabel(Card_Template);
        Card_BankName->setObjectName("Card_BankName");
        Card_BankName->setGeometry(QRect(150, 10, 141, 41));
        QFont font5;
        font5.setPointSize(10);
        Card_BankName->setFont(font5);
        Card_BankName->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        Card_BankName->setScaledContents(false);
        Card_BankName->setAlignment(Qt::AlignRight|Qt::AlignTop|Qt::AlignTrailing);
        Card_BankName->setMargin(9);
        CardsScroll->setWidget(CardsScrollAreaWidgetContent);
        cardInfoWidget = new QWidget(AccountsTab);
        cardInfoWidget->setObjectName("cardInfoWidget");
        cardInfoWidget->setGeometry(QRect(390, 10, 211, 221));
        Card_Name = new QLabel(cardInfoWidget);
        Card_Name->setObjectName("Card_Name");
        Card_Name->setGeometry(QRect(80, 10, 121, 16));
        Card_Status = new QLabel(cardInfoWidget);
        Card_Status->setObjectName("Card_Status");
        Card_Status->setGeometry(QRect(80, 30, 121, 16));
        Card_MGPM = new QLabel(cardInfoWidget);
        Card_MGPM->setObjectName("Card_MGPM");
        Card_MGPM->setGeometry(QRect(80, 50, 121, 16));
        Card_expiration_date = new QLabel(cardInfoWidget);
        Card_expiration_date->setObjectName("Card_expiration_date");
        Card_expiration_date->setGeometry(QRect(80, 190, 121, 16));
        Card_Iban = new QLabel(cardInfoWidget);
        Card_Iban->setObjectName("Card_Iban");
        Card_Iban->setGeometry(QRect(80, 170, 121, 16));
        main->addTab(AccountsTab, QString());
        HistoryTab_2 = new QWidget();
        HistoryTab_2->setObjectName("HistoryTab_2");
        historyScrollArea = new QScrollArea(HistoryTab_2);
        historyScrollArea->setObjectName("historyScrollArea");
        historyScrollArea->setGeometry(QRect(10, 0, 411, 231));
        QSizePolicy sizePolicy1(QSizePolicy::Policy::Expanding, QSizePolicy::Policy::Expanding);
        sizePolicy1.setHorizontalStretch(0);
        sizePolicy1.setVerticalStretch(0);
        sizePolicy1.setHeightForWidth(historyScrollArea->sizePolicy().hasHeightForWidth());
        historyScrollArea->setSizePolicy(sizePolicy1);
        historyScrollArea->setAcceptDrops(false);
        historyScrollArea->setLayoutDirection(Qt::LeftToRight);
        historyScrollArea->setFrameShape(QFrame::NoFrame);
        historyScrollArea->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        historyScrollArea->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        historyScrollArea->setSizeAdjustPolicy(QAbstractScrollArea::AdjustToContentsOnFirstShow);
        historyScrollArea->setWidgetResizable(true);
        historyScrollArea->setAlignment(Qt::AlignCenter);
        historyScrollArea->setProperty("LastItem_HorizontalPos", QVariant(0));
        HistoryScrollAreaWidgetContents = new QWidget();
        HistoryScrollAreaWidgetContents->setObjectName("HistoryScrollAreaWidgetContents");
        HistoryScrollAreaWidgetContents->setGeometry(QRect(0, 0, 411, 231));
        TransactionTemplateWidget = new QWidget(HistoryScrollAreaWidgetContents);
        TransactionTemplateWidget->setObjectName("TransactionTemplateWidget");
        TransactionTemplateWidget->setGeometry(QRect(0, 0, 401, 50));
        TransactionTemplateWidget->setMinimumSize(QSize(401, 50));
        History_IMG_logo = new QLabel(TransactionTemplateWidget);
        History_IMG_logo->setObjectName("History_IMG_logo");
        History_IMG_logo->setGeometry(QRect(10, 5, 55, 41));
        History_ammount = new QLabel(TransactionTemplateWidget);
        History_ammount->setObjectName("History_ammount");
        History_ammount->setGeometry(QRect(240, 20, 91, 20));
        History_ammount->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        History_value_type = new QLabel(TransactionTemplateWidget);
        History_value_type->setObjectName("History_value_type");
        History_value_type->setGeometry(QRect(340, 20, 61, 20));
        History_value_type->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        History_PAN_from = new QLabel(TransactionTemplateWidget);
        History_PAN_from->setObjectName("History_PAN_from");
        History_PAN_from->setGeometry(QRect(60, 10, 181, 16));
        QFont font6;
        font6.setPointSize(7);
        History_PAN_from->setFont(font6);
        History_PAN_from->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        History_PAN_to = new QLabel(TransactionTemplateWidget);
        History_PAN_to->setObjectName("History_PAN_to");
        History_PAN_to->setGeometry(QRect(60, 30, 181, 16));
        History_PAN_to->setFont(font6);
        History_PAN_to->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        historyScrollArea->setWidget(HistoryScrollAreaWidgetContents);
        filterWidget_2 = new QFrame(HistoryTab_2);
        filterWidget_2->setObjectName("filterWidget_2");
        filterWidget_2->setGeometry(QRect(430, 0, 171, 231));
        filterWidget_2->setFrameShape(QFrame::StyledPanel);
        filterWidget_2->setFrameShadow(QFrame::Raised);
        incomeCheckBox_2 = new QCheckBox(filterWidget_2);
        incomeCheckBox_2->setObjectName("incomeCheckBox_2");
        incomeCheckBox_2->setGeometry(QRect(10, 0, 81, 20));
        expensesCheckBox_2 = new QCheckBox(filterWidget_2);
        expensesCheckBox_2->setObjectName("expensesCheckBox_2");
        expensesCheckBox_2->setGeometry(QRect(90, 0, 81, 20));
        cardsCheckBox_2 = new QComboBox(filterWidget_2);
        cardsCheckBox_2->addItem(QString());
        cardsCheckBox_2->addItem(QString());
        cardsCheckBox_2->addItem(QString());
        cardsCheckBox_2->setObjectName("cardsCheckBox_2");
        cardsCheckBox_2->setGeometry(QRect(10, 50, 151, 22));
        label_6 = new QLabel(filterWidget_2);
        label_6->setObjectName("label_6");
        label_6->setGeometry(QRect(10, 30, 101, 16));
        load_more_button_2 = new QPushButton(filterWidget_2);
        load_more_button_2->setObjectName("load_more_button_2");
        load_more_button_2->setGeometry(QRect(10, 190, 141, 28));
        main->addTab(HistoryTab_2, QString());
        DepositeTab_2 = new QWidget();
        DepositeTab_2->setObjectName("DepositeTab_2");
        CardsScroll_4 = new QScrollArea(DepositeTab_2);
        CardsScroll_4->setObjectName("CardsScroll_4");
        CardsScroll_4->setGeometry(QRect(10, 10, 361, 201));
        CardsScroll_4->setFrameShadow(QFrame::Sunken);
        CardsScroll_4->setWidgetResizable(true);
        scrollAreaWidgetContents_6 = new QWidget();
        scrollAreaWidgetContents_6->setObjectName("scrollAreaWidgetContents_6");
        scrollAreaWidgetContents_6->setGeometry(QRect(0, 0, 359, 199));
        Card_Dep1_2 = new QWidget(scrollAreaWidgetContents_6);
        Card_Dep1_2->setObjectName("Card_Dep1_2");
        Card_Dep1_2->setGeometry(QRect(0, 0, 361, 91));
        CardsScroll_4->setWidget(scrollAreaWidgetContents_6);
        main->addTab(DepositeTab_2, QString());
        OtherTab_2 = new QWidget();
        OtherTab_2->setObjectName("OtherTab_2");
        main->addTab(OtherTab_2, QString());
        msg_box = new QLabel(MainWindow);
        msg_box->setObjectName("msg_box");
        msg_box->setGeometry(QRect(480, 640, 231, 61));
        msg_box->setFont(font1);
        msg_box->setScaledContents(false);
        msg_box->setWordWrap(true);
        msg_box->setMargin(0);
        msg_box->setIndent(1);
        TransactionWidget = new QWidget(MainWindow);
        TransactionWidget->setObjectName("TransactionWidget");
        TransactionWidget->setGeometry(QRect(620, 320, 611, 311));
        MainTransactionFrame = new QFrame(TransactionWidget);
        MainTransactionFrame->setObjectName("MainTransactionFrame");
        MainTransactionFrame->setGeometry(QRect(170, 40, 381, 221));
        MainTransactionFrame->setAutoFillBackground(false);
        MainTransactionFrame->setFrameShape(QFrame::StyledPanel);
        MainTransactionFrame->setFrameShadow(QFrame::Raised);
        UserCardsBox = new QComboBox(MainTransactionFrame);
        UserCardsBox->setObjectName("UserCardsBox");
        UserCardsBox->setGeometry(QRect(20, 70, 131, 21));
        TransactionFrameName = new QLabel(MainTransactionFrame);
        TransactionFrameName->setObjectName("TransactionFrameName");
        TransactionFrameName->setGeometry(QRect(120, 10, 161, 31));
        QFont font7;
        font7.setPointSize(11);
        TransactionFrameName->setFont(font7);
        Transaction_From = new QLabel(MainTransactionFrame);
        Transaction_From->setObjectName("Transaction_From");
        Transaction_From->setGeometry(QRect(30, 50, 55, 16));
        Transaction_To = new QLabel(MainTransactionFrame);
        Transaction_To->setObjectName("Transaction_To");
        Transaction_To->setGeometry(QRect(190, 50, 55, 16));
        PAN_to = new QLineEdit(MainTransactionFrame);
        PAN_to->setObjectName("PAN_to");
        PAN_to->setGeometry(QRect(190, 70, 161, 22));
        AmountSpin = new QDoubleSpinBox(MainTransactionFrame);
        AmountSpin->setObjectName("AmountSpin");
        AmountSpin->setGeometry(QRect(110, 130, 151, 22));
        AmountSpin->setMaximum(250000.000000000000000);
        AmountLabel = new QLabel(MainTransactionFrame);
        AmountLabel->setObjectName("AmountLabel");
        AmountLabel->setGeometry(QRect(110, 110, 55, 16));
        TransactionRequestButton = new QPushButton(MainTransactionFrame);
        TransactionRequestButton->setObjectName("TransactionRequestButton");
        TransactionRequestButton->setGeometry(QRect(190, 180, 93, 28));
        TransactionRequestButton->setProperty("isIBAN", QVariant(false));
        PIN_Edit = new QLineEdit(MainTransactionFrame);
        PIN_Edit->setObjectName("PIN_Edit");
        PIN_Edit->setGeometry(QRect(130, 180, 51, 22));
        label_3 = new QLabel(MainTransactionFrame);
        label_3->setObjectName("label_3");
        label_3->setGeometry(QRect(90, 180, 31, 16));
        BackFromTransactionWindow = new QPushButton(TransactionWidget);
        BackFromTransactionWindow->setObjectName("BackFromTransactionWindow");
        BackFromTransactionWindow->setGeometry(QRect(20, 10, 93, 28));

        retranslateUi(MainWindow);

        main->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QDialog *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "MakoStream's Bank", nullptr));
        logo_main->setText(QString());
        LoginButton->setText(QCoreApplication::translate("MainWindow", "Login", nullptr));
        ForgedPasswodButton->setText(QCoreApplication::translate("MainWindow", "forgot password?", nullptr));
        login_label->setText(QCoreApplication::translate("MainWindow", "login", nullptr));
        login_line_edit->setInputMask(QString());
        login_line_edit->setText(QString());
        label->setText(QCoreApplication::translate("MainWindow", "Some project", nullptr));
        label_unput_password->setText(QCoreApplication::translate("MainWindow", "password", nullptr));
        RegisterButton->setText(QCoreApplication::translate("MainWindow", "registration", nullptr));
        label_login->setText(QCoreApplication::translate("MainWindow", "login", nullptr));
        user_id_value->setText(QCoreApplication::translate("MainWindow", "000000", nullptr));
        user_id_label->setText(QCoreApplication::translate("MainWindow", "u-id:", nullptr));
        session_id_label->setText(QCoreApplication::translate("MainWindow", "s-id:", nullptr));
        session_id_value->setText(QCoreApplication::translate("MainWindow", "000000", nullptr));
        RegisterButtonCompl->setText(QCoreApplication::translate("MainWindow", "Register", nullptr));
        logo_main_2->setText(QString());
        ProjectNameLabel->setText(QCoreApplication::translate("MainWindow", "Some project", nullptr));
        RegLabel1->setText(QCoreApplication::translate("MainWindow", "Registration", nullptr));
        NameLabel->setText(QCoreApplication::translate("MainWindow", "Name*", nullptr));
        SurnameLabel->setText(QCoreApplication::translate("MainWindow", "Surname*", nullptr));
        LoginLabel->setText(QCoreApplication::translate("MainWindow", "Login*", nullptr));
        label_2->setText(QCoreApplication::translate("MainWindow", "Password*", nullptr));
        BackToLoginButton->setText(QCoreApplication::translate("MainWindow", "Back", nullptr));
        TransactionIBAN->setText(QCoreApplication::translate("MainWindow", "IBAN transaction", nullptr));
        TransactionPAN->setText(QCoreApplication::translate("MainWindow", "PAN transaction", nullptr));
        TransactionOther->setText(QCoreApplication::translate("MainWindow", "Other transaction", nullptr));
        LogoutButton->setText(QCoreApplication::translate("MainWindow", "Logout", nullptr));
        updateButton->setText(QCoreApplication::translate("MainWindow", "Update", nullptr));
        user_id_value_3->setText(QCoreApplication::translate("MainWindow", "000000", nullptr));
        user_id_label_3->setText(QCoreApplication::translate("MainWindow", "u-id:", nullptr));
        session_id_value_3->setText(QCoreApplication::translate("MainWindow", "000000", nullptr));
        session_id_label_3->setText(QCoreApplication::translate("MainWindow", "s-id:", nullptr));
        Card_image->setText(QString());
        Card_Value->setText(QCoreApplication::translate("MainWindow", "card_value", nullptr));
        Card_Value_Type->setText(QCoreApplication::translate("MainWindow", "UAH", nullptr));
        Card_PAN->setText(QCoreApplication::translate("MainWindow", "0000 0000 0000 0000", nullptr));
        Card_BankName->setText(QCoreApplication::translate("MainWindow", "Stream Bank", nullptr));
        Card_Name->setText(QCoreApplication::translate("MainWindow", "Card_Name", nullptr));
        Card_Status->setText(QCoreApplication::translate("MainWindow", "err_Card_Status", nullptr));
        Card_MGPM->setText(QCoreApplication::translate("MainWindow", "Card_Description", nullptr));
        Card_expiration_date->setText(QCoreApplication::translate("MainWindow", "err_Card_expiration_date", nullptr));
        Card_Iban->setText(QCoreApplication::translate("MainWindow", "err_Card_IBAN", nullptr));
        main->setTabText(main->indexOf(AccountsTab), QCoreApplication::translate("MainWindow", "Accounts", nullptr));
        History_IMG_logo->setText(QCoreApplication::translate("MainWindow", "Logo", nullptr));
        History_ammount->setText(QCoreApplication::translate("MainWindow", "err_ammount", nullptr));
        History_value_type->setText(QCoreApplication::translate("MainWindow", "err_value_type", nullptr));
        History_PAN_from->setText(QCoreApplication::translate("MainWindow", "err_card_lastPAN", nullptr));
        History_PAN_to->setText(QCoreApplication::translate("MainWindow", "err_card_lastPAN", nullptr));
        incomeCheckBox_2->setText(QCoreApplication::translate("MainWindow", "income", nullptr));
        expensesCheckBox_2->setText(QCoreApplication::translate("MainWindow", "expenses", nullptr));
        cardsCheckBox_2->setItemText(0, QCoreApplication::translate("MainWindow", "0000000000000001", nullptr));
        cardsCheckBox_2->setItemText(1, QCoreApplication::translate("MainWindow", "0000000000000002", nullptr));
        cardsCheckBox_2->setItemText(2, QCoreApplication::translate("MainWindow", "0000000000000003", nullptr));

        label_6->setText(QCoreApplication::translate("MainWindow", "Cards:", nullptr));
        load_more_button_2->setText(QCoreApplication::translate("MainWindow", "load more...", nullptr));
        main->setTabText(main->indexOf(HistoryTab_2), QCoreApplication::translate("MainWindow", "History", nullptr));
        main->setTabText(main->indexOf(DepositeTab_2), QCoreApplication::translate("MainWindow", "Deposite", nullptr));
        main->setTabText(main->indexOf(OtherTab_2), QCoreApplication::translate("MainWindow", "Other", nullptr));
        msg_box->setText(QCoreApplication::translate("MainWindow", "msg text", nullptr));
        TransactionFrameName->setText(QCoreApplication::translate("MainWindow", "PAN Transaction", nullptr));
        Transaction_From->setText(QCoreApplication::translate("MainWindow", "From", nullptr));
        Transaction_To->setText(QCoreApplication::translate("MainWindow", "To*", nullptr));
        AmountLabel->setText(QCoreApplication::translate("MainWindow", "Amount", nullptr));
        TransactionRequestButton->setText(QCoreApplication::translate("MainWindow", "Request", nullptr));
        label_3->setText(QCoreApplication::translate("MainWindow", "PIN:", nullptr));
        BackFromTransactionWindow->setText(QCoreApplication::translate("MainWindow", "Back", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_WINDOW_H
