/********************************************************************************
** Form generated from reading UI file 'Window.ui'
**
** Created by: Qt User Interface Compiler version 6.10.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_WINDOW_H
#define UI_WINDOW_H

#include <QtCore/QVariant>
#include <QtGui/QIcon>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QCommandLinkButton>
#include <QtWidgets/QDialog>
#include <QtWidgets/QFrame>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QScrollArea>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *loginWidget;
    QLabel *logo_main;
    QPushButton *LoginButton;
    QCommandLinkButton *ForgedPasswodButton;
    QLabel *login_label;
    QLineEdit *login_line_edit;
    QLabel *label;
    QLabel *label_unput_password;
    QCommandLinkButton *RegisterButton;
    QLabel *label_login;
    QLineEdit *password_line_edit;
    QFrame *SessionInfoFrame;
    QLabel *user_id_value;
    QLabel *user_id_label;
    QLabel *session_id_label;
    QLabel *session_id_value;
    QWidget *RegWidget;
    QPushButton *RegisterButtonCompl;
    QLabel *logo_main_2;
    QLineEdit *NameEdit;
    QLineEdit *SurnameEdit;
    QLabel *ProjectNameLabel;
    QLabel *RegLabel1;
    QLabel *NameLabel;
    QLabel *SurnameLabel;
    QLabel *LoginLabel;
    QLineEdit *LoginEdit;
    QLabel *label_2;
    QLineEdit *PasswordEdit;
    QPushButton *BackToLoginButton;
    QWidget *MainMenuWidget;
    QWidget *mainMenuWidget;
    QPushButton *pushButton_7;
    QPushButton *pushButton_8;
    QPushButton *pushButton_9;
    QWidget *supportInfoWidget;
    QLabel *user_id_value_3;
    QLabel *user_id_label_3;
    QLabel *session_id_value_3;
    QLabel *session_id_label_3;
    QTabWidget *main;
    QWidget *AccountsTab_2;
    QScrollArea *CardsScroll_3;
    QWidget *scrollAreaWidgetContents_4;
    QWidget *Card_Template_2;
    QLabel *Card1_image_2;
    QLabel *Card_Value_2;
    QLabel *Card_Value_Type_2;
    QLabel *Card_PAN_2;
    QLabel *Card_BankName_2;
    QWidget *cardInfoWidget_2;
    QLabel *Card_Name_2;
    QLabel *Card_Status_2;
    QLabel *Card_MGPM_2;
    QLabel *Card_expiration_date_2;
    QLabel *Card_Iban_2;
    QWidget *HistoryTab_2;
    QScrollArea *historyScrollArea_2;
    QWidget *scrollAreaWidgetContents_5;
    QWidget *historyEvent1widget_2;
    QLabel *IMG_logo_2;
    QLabel *ammount_3;
    QLabel *value_type_2;
    QLabel *ammount_4;
    QPushButton *load_more_button_2;
    QFrame *filterWidget_2;
    QCheckBox *incomeCheckBox_2;
    QCheckBox *expensesCheckBox_2;
    QComboBox *cardsCheckBox_2;
    QLabel *label_6;
    QWidget *DepositeTab_2;
    QScrollArea *CardsScroll_4;
    QWidget *scrollAreaWidgetContents_6;
    QWidget *Card_Dep1_2;
    QWidget *OtherTab_2;
    QLabel *msg_box;

    void setupUi(QDialog *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName("MainWindow");
        MainWindow->setEnabled(true);
        MainWindow->resize(1250, 671);
        QSizePolicy sizePolicy(QSizePolicy::Policy::Preferred, QSizePolicy::Policy::Ignored);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(MainWindow->sizePolicy().hasHeightForWidth());
        MainWindow->setSizePolicy(sizePolicy);
        MainWindow->setMinimumSize(QSize(620, 315));
        MainWindow->setMaximumSize(QSize(6180, 3150));
        QFont font;
        font.setPointSize(8);
        MainWindow->setFont(font);
        MainWindow->setContextMenuPolicy(Qt::NoContextMenu);
        MainWindow->setAcceptDrops(false);
        QIcon icon;
        icon.addFile(QString::fromUtf8("C:/Users/Admin/OneDrive/Pictures/GlassCubeRed1.png"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        MainWindow->setWindowIcon(icon);
        MainWindow->setWindowOpacity(2.000000000000000);
        loginWidget = new QWidget(MainWindow);
        loginWidget->setObjectName("loginWidget");
        loginWidget->setGeometry(QRect(0, 0, 611, 311));
        logo_main = new QLabel(loginWidget);
        logo_main->setObjectName("logo_main");
        logo_main->setGeometry(QRect(-100, -50, 561, 321));
        logo_main->setPixmap(QPixmap(QString::fromUtf8("C:/Users/Admin/OneDrive/Pictures/GlassCubeRed.png")));
        logo_main->setScaledContents(true);
        logo_main->setWordWrap(false);
        LoginButton = new QPushButton(loginWidget);
        LoginButton->setObjectName("LoginButton");
        LoginButton->setGeometry(QRect(440, 265, 93, 28));
        ForgedPasswodButton = new QCommandLinkButton(loginWidget);
        ForgedPasswodButton->setObjectName("ForgedPasswodButton");
        ForgedPasswodButton->setGeometry(QRect(420, 184, 151, 31));
        QFont font1;
        font1.setFamilies({QString::fromUtf8("Segoe UI")});
        font1.setPointSize(8);
        ForgedPasswodButton->setFont(font1);
        ForgedPasswodButton->setLayoutDirection(Qt::LeftToRight);
        ForgedPasswodButton->setIconSize(QSize(0, 0));
        login_label = new QLabel(loginWidget);
        login_label->setObjectName("login_label");
        login_label->setEnabled(true);
        login_label->setGeometry(QRect(352, 24, 231, 41));
        QFont font2;
        font2.setFamilies({QString::fromUtf8("MS Reference Sans Serif")});
        font2.setPointSize(10);
        font2.setBold(true);
        font2.setStrikeOut(false);
        font2.setKerning(true);
        font2.setStyleStrategy(QFont::PreferDefault);
        login_label->setFont(font2);
        login_label->setFocusPolicy(Qt::NoFocus);
        login_label->setAcceptDrops(false);
        login_label->setLayoutDirection(Qt::LeftToRight);
        login_label->setScaledContents(false);
        login_label->setWordWrap(false);
        login_line_edit = new QLineEdit(loginWidget);
        login_line_edit->setObjectName("login_line_edit");
        login_line_edit->setGeometry(QRect(430, 135, 161, 21));
        login_line_edit->setMaxLength(34);
        label = new QLabel(loginWidget);
        label->setObjectName("label");
        label->setEnabled(true);
        label->setGeometry(QRect(352, 1, 231, 41));
        QFont font3;
        font3.setFamilies({QString::fromUtf8("MS Reference Sans Serif")});
        font3.setPointSize(12);
        font3.setBold(true);
        font3.setStrikeOut(false);
        font3.setKerning(true);
        font3.setStyleStrategy(QFont::PreferDefault);
        label->setFont(font3);
        label->setFocusPolicy(Qt::NoFocus);
        label->setAcceptDrops(false);
        label->setLayoutDirection(Qt::LeftToRight);
        label->setScaledContents(false);
        label->setWordWrap(false);
        label_unput_password = new QLabel(loginWidget);
        label_unput_password->setObjectName("label_unput_password");
        label_unput_password->setGeometry(QRect(370, 165, 61, 16));
        RegisterButton = new QCommandLinkButton(loginWidget);
        RegisterButton->setObjectName("RegisterButton");
        RegisterButton->setGeometry(QRect(440, 215, 111, 31));
        RegisterButton->setFont(font1);
        RegisterButton->setLayoutDirection(Qt::LeftToRight);
        RegisterButton->setIconSize(QSize(0, 0));
        label_login = new QLabel(loginWidget);
        label_login->setObjectName("label_login");
        label_login->setGeometry(QRect(370, 135, 55, 16));
        password_line_edit = new QLineEdit(loginWidget);
        password_line_edit->setObjectName("password_line_edit");
        password_line_edit->setGeometry(QRect(430, 164, 161, 21));
        password_line_edit->setMaxLength(34);
        SessionInfoFrame = new QFrame(MainWindow);
        SessionInfoFrame->setObjectName("SessionInfoFrame");
        SessionInfoFrame->setEnabled(true);
        SessionInfoFrame->setGeometry(QRect(0, 280, 81, 31));
        SessionInfoFrame->setFrameShape(QFrame::StyledPanel);
        SessionInfoFrame->setFrameShadow(QFrame::Raised);
        user_id_value = new QLabel(SessionInfoFrame);
        user_id_value->setObjectName("user_id_value");
        user_id_value->setGeometry(QRect(30, 0, 42, 16));
        user_id_label = new QLabel(SessionInfoFrame);
        user_id_label->setObjectName("user_id_label");
        user_id_label->setGeometry(QRect(0, 0, 27, 16));
        session_id_label = new QLabel(SessionInfoFrame);
        session_id_label->setObjectName("session_id_label");
        session_id_label->setGeometry(QRect(0, 15, 26, 16));
        session_id_value = new QLabel(SessionInfoFrame);
        session_id_value->setObjectName("session_id_value");
        session_id_value->setGeometry(QRect(30, 15, 42, 16));
        RegWidget = new QWidget(MainWindow);
        RegWidget->setObjectName("RegWidget");
        RegWidget->setGeometry(QRect(0, 320, 611, 311));
        RegisterButtonCompl = new QPushButton(RegWidget);
        RegisterButtonCompl->setObjectName("RegisterButtonCompl");
        RegisterButtonCompl->setGeometry(QRect(450, 260, 93, 28));
        logo_main_2 = new QLabel(RegWidget);
        logo_main_2->setObjectName("logo_main_2");
        logo_main_2->setGeometry(QRect(-90, -40, 561, 321));
        logo_main_2->setPixmap(QPixmap(QString::fromUtf8("C:/Users/Admin/OneDrive/Pictures/GlassCubeRed.png")));
        logo_main_2->setScaledContents(true);
        logo_main_2->setWordWrap(false);
        NameEdit = new QLineEdit(RegWidget);
        NameEdit->setObjectName("NameEdit");
        NameEdit->setGeometry(QRect(370, 100, 101, 22));
        SurnameEdit = new QLineEdit(RegWidget);
        SurnameEdit->setObjectName("SurnameEdit");
        SurnameEdit->setGeometry(QRect(480, 100, 101, 22));
        ProjectNameLabel = new QLabel(RegWidget);
        ProjectNameLabel->setObjectName("ProjectNameLabel");
        ProjectNameLabel->setEnabled(true);
        ProjectNameLabel->setGeometry(QRect(360, 10, 231, 41));
        ProjectNameLabel->setFont(font3);
        ProjectNameLabel->setFocusPolicy(Qt::NoFocus);
        ProjectNameLabel->setAcceptDrops(false);
        ProjectNameLabel->setLayoutDirection(Qt::LeftToRight);
        ProjectNameLabel->setScaledContents(false);
        ProjectNameLabel->setWordWrap(false);
        RegLabel1 = new QLabel(RegWidget);
        RegLabel1->setObjectName("RegLabel1");
        RegLabel1->setEnabled(true);
        RegLabel1->setGeometry(QRect(360, 33, 231, 41));
        RegLabel1->setFont(font2);
        RegLabel1->setFocusPolicy(Qt::NoFocus);
        RegLabel1->setAcceptDrops(false);
        RegLabel1->setLayoutDirection(Qt::LeftToRight);
        RegLabel1->setScaledContents(false);
        RegLabel1->setWordWrap(false);
        NameLabel = new QLabel(RegWidget);
        NameLabel->setObjectName("NameLabel");
        NameLabel->setGeometry(QRect(370, 80, 55, 16));
        SurnameLabel = new QLabel(RegWidget);
        SurnameLabel->setObjectName("SurnameLabel");
        SurnameLabel->setGeometry(QRect(486, 80, 61, 16));
        LoginLabel = new QLabel(RegWidget);
        LoginLabel->setObjectName("LoginLabel");
        LoginLabel->setGeometry(QRect(370, 130, 55, 16));
        LoginEdit = new QLineEdit(RegWidget);
        LoginEdit->setObjectName("LoginEdit");
        LoginEdit->setGeometry(QRect(370, 150, 113, 22));
        label_2 = new QLabel(RegWidget);
        label_2->setObjectName("label_2");
        label_2->setGeometry(QRect(370, 180, 55, 16));
        PasswordEdit = new QLineEdit(RegWidget);
        PasswordEdit->setObjectName("PasswordEdit");
        PasswordEdit->setGeometry(QRect(370, 200, 113, 22));
        BackToLoginButton = new QPushButton(RegWidget);
        BackToLoginButton->setObjectName("BackToLoginButton");
        BackToLoginButton->setGeometry(QRect(10, 10, 93, 28));
        logo_main_2->raise();
        RegisterButtonCompl->raise();
        NameEdit->raise();
        SurnameEdit->raise();
        ProjectNameLabel->raise();
        RegLabel1->raise();
        NameLabel->raise();
        SurnameLabel->raise();
        LoginLabel->raise();
        LoginEdit->raise();
        label_2->raise();
        PasswordEdit->raise();
        BackToLoginButton->raise();
        MainMenuWidget = new QWidget(MainWindow);
        MainMenuWidget->setObjectName("MainMenuWidget");
        MainMenuWidget->setGeometry(QRect(620, 0, 611, 311));
        mainMenuWidget = new QWidget(MainMenuWidget);
        mainMenuWidget->setObjectName("mainMenuWidget");
        mainMenuWidget->setGeometry(QRect(0, 270, 611, 41));
        pushButton_7 = new QPushButton(mainMenuWidget);
        pushButton_7->setObjectName("pushButton_7");
        pushButton_7->setGeometry(QRect(10, 10, 141, 28));
        pushButton_8 = new QPushButton(mainMenuWidget);
        pushButton_8->setObjectName("pushButton_8");
        pushButton_8->setGeometry(QRect(160, 10, 141, 28));
        pushButton_9 = new QPushButton(mainMenuWidget);
        pushButton_9->setObjectName("pushButton_9");
        pushButton_9->setGeometry(QRect(310, 10, 141, 28));
        supportInfoWidget = new QWidget(MainMenuWidget);
        supportInfoWidget->setObjectName("supportInfoWidget");
        supportInfoWidget->setGeometry(QRect(430, 0, 181, 21));
        user_id_value_3 = new QLabel(supportInfoWidget);
        user_id_value_3->setObjectName("user_id_value_3");
        user_id_value_3->setGeometry(QRect(30, 0, 42, 16));
        user_id_label_3 = new QLabel(supportInfoWidget);
        user_id_label_3->setObjectName("user_id_label_3");
        user_id_label_3->setGeometry(QRect(0, 0, 27, 16));
        session_id_value_3 = new QLabel(supportInfoWidget);
        session_id_value_3->setObjectName("session_id_value_3");
        session_id_value_3->setGeometry(QRect(130, 0, 42, 16));
        session_id_label_3 = new QLabel(supportInfoWidget);
        session_id_label_3->setObjectName("session_id_label_3");
        session_id_label_3->setGeometry(QRect(100, 0, 26, 16));
        main = new QTabWidget(MainMenuWidget);
        main->setObjectName("main");
        main->setEnabled(true);
        main->setGeometry(QRect(0, 0, 621, 271));
        main->setLayoutDirection(Qt::LeftToRight);
        main->setTabPosition(QTabWidget::North);
        main->setUsesScrollButtons(false);
        main->setDocumentMode(false);
        main->setTabsClosable(false);
        AccountsTab_2 = new QWidget();
        AccountsTab_2->setObjectName("AccountsTab_2");
        CardsScroll_3 = new QScrollArea(AccountsTab_2);
        CardsScroll_3->setObjectName("CardsScroll_3");
        CardsScroll_3->setGeometry(QRect(10, 10, 361, 201));
        CardsScroll_3->setFrameShadow(QFrame::Sunken);
        CardsScroll_3->setLineWidth(0);
        CardsScroll_3->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        CardsScroll_3->setHorizontalScrollBarPolicy(Qt::ScrollBarAsNeeded);
        CardsScroll_3->setSizeAdjustPolicy(QAbstractScrollArea::AdjustIgnored);
        CardsScroll_3->setWidgetResizable(true);
        scrollAreaWidgetContents_4 = new QWidget();
        scrollAreaWidgetContents_4->setObjectName("scrollAreaWidgetContents_4");
        scrollAreaWidgetContents_4->setGeometry(QRect(0, 0, 359, 199));
        Card_Template_2 = new QWidget(scrollAreaWidgetContents_4);
        Card_Template_2->setObjectName("Card_Template_2");
        Card_Template_2->setEnabled(true);
        Card_Template_2->setGeometry(QRect(0, 0, 361, 201));
        Card1_image_2 = new QLabel(Card_Template_2);
        Card1_image_2->setObjectName("Card1_image_2");
        Card1_image_2->setGeometry(QRect(40, 0, 271, 161));
        Card1_image_2->setPixmap(QPixmap(QString::fromUtf8("UI/resources/images/Untitled17_20251029201549.png")));
        Card1_image_2->setScaledContents(true);
        Card1_image_2->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignTop);
        Card_Value_2 = new QLabel(Card_Template_2);
        Card_Value_2->setObjectName("Card_Value_2");
        Card_Value_2->setGeometry(QRect(60, 160, 91, 31));
        Card_Value_Type_2 = new QLabel(Card_Template_2);
        Card_Value_Type_2->setObjectName("Card_Value_Type_2");
        Card_Value_Type_2->setGeometry(QRect(180, 160, 91, 31));
        Card_PAN_2 = new QLabel(Card_Template_2);
        Card_PAN_2->setObjectName("Card_PAN_2");
        Card_PAN_2->setGeometry(QRect(74, 90, 201, 31));
        QFont font4;
        font4.setPointSize(12);
        Card_PAN_2->setFont(font4);
        Card_PAN_2->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        Card_BankName_2 = new QLabel(Card_Template_2);
        Card_BankName_2->setObjectName("Card_BankName_2");
        Card_BankName_2->setGeometry(QRect(150, 10, 141, 41));
        QFont font5;
        font5.setPointSize(10);
        Card_BankName_2->setFont(font5);
        Card_BankName_2->setStyleSheet(QString::fromUtf8("color: rgb(255, 255, 255);"));
        Card_BankName_2->setScaledContents(false);
        Card_BankName_2->setAlignment(Qt::AlignRight|Qt::AlignTop|Qt::AlignTrailing);
        Card_BankName_2->setMargin(9);
        CardsScroll_3->setWidget(scrollAreaWidgetContents_4);
        cardInfoWidget_2 = new QWidget(AccountsTab_2);
        cardInfoWidget_2->setObjectName("cardInfoWidget_2");
        cardInfoWidget_2->setGeometry(QRect(390, 10, 211, 221));
        Card_Name_2 = new QLabel(cardInfoWidget_2);
        Card_Name_2->setObjectName("Card_Name_2");
        Card_Name_2->setGeometry(QRect(80, 10, 121, 16));
        Card_Status_2 = new QLabel(cardInfoWidget_2);
        Card_Status_2->setObjectName("Card_Status_2");
        Card_Status_2->setGeometry(QRect(80, 30, 121, 16));
        Card_MGPM_2 = new QLabel(cardInfoWidget_2);
        Card_MGPM_2->setObjectName("Card_MGPM_2");
        Card_MGPM_2->setGeometry(QRect(80, 50, 121, 16));
        Card_expiration_date_2 = new QLabel(cardInfoWidget_2);
        Card_expiration_date_2->setObjectName("Card_expiration_date_2");
        Card_expiration_date_2->setGeometry(QRect(80, 190, 121, 16));
        Card_Iban_2 = new QLabel(cardInfoWidget_2);
        Card_Iban_2->setObjectName("Card_Iban_2");
        Card_Iban_2->setGeometry(QRect(80, 170, 121, 16));
        main->addTab(AccountsTab_2, QString());
        HistoryTab_2 = new QWidget();
        HistoryTab_2->setObjectName("HistoryTab_2");
        historyScrollArea_2 = new QScrollArea(HistoryTab_2);
        historyScrollArea_2->setObjectName("historyScrollArea_2");
        historyScrollArea_2->setGeometry(QRect(10, 0, 411, 231));
        historyScrollArea_2->setLayoutDirection(Qt::LeftToRight);
        historyScrollArea_2->setVerticalScrollBarPolicy(Qt::ScrollBarAsNeeded);
        historyScrollArea_2->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        historyScrollArea_2->setWidgetResizable(true);
        historyScrollArea_2->setAlignment(Qt::AlignCenter);
        scrollAreaWidgetContents_5 = new QWidget();
        scrollAreaWidgetContents_5->setObjectName("scrollAreaWidgetContents_5");
        scrollAreaWidgetContents_5->setGeometry(QRect(0, 0, 409, 229));
        historyEvent1widget_2 = new QWidget(scrollAreaWidgetContents_5);
        historyEvent1widget_2->setObjectName("historyEvent1widget_2");
        historyEvent1widget_2->setGeometry(QRect(0, 0, 401, 51));
        IMG_logo_2 = new QLabel(historyEvent1widget_2);
        IMG_logo_2->setObjectName("IMG_logo_2");
        IMG_logo_2->setGeometry(QRect(10, 5, 55, 41));
        ammount_3 = new QLabel(historyEvent1widget_2);
        ammount_3->setObjectName("ammount_3");
        ammount_3->setGeometry(QRect(240, 20, 91, 20));
        ammount_3->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        value_type_2 = new QLabel(historyEvent1widget_2);
        value_type_2->setObjectName("value_type_2");
        value_type_2->setGeometry(QRect(340, 20, 61, 20));
        value_type_2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        ammount_4 = new QLabel(historyEvent1widget_2);
        ammount_4->setObjectName("ammount_4");
        ammount_4->setGeometry(QRect(90, 20, 91, 20));
        ammount_4->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        load_more_button_2 = new QPushButton(scrollAreaWidgetContents_5);
        load_more_button_2->setObjectName("load_more_button_2");
        load_more_button_2->setGeometry(QRect(110, 60, 141, 28));
        historyScrollArea_2->setWidget(scrollAreaWidgetContents_5);
        filterWidget_2 = new QFrame(HistoryTab_2);
        filterWidget_2->setObjectName("filterWidget_2");
        filterWidget_2->setGeometry(QRect(430, 0, 171, 231));
        filterWidget_2->setFrameShape(QFrame::StyledPanel);
        filterWidget_2->setFrameShadow(QFrame::Raised);
        incomeCheckBox_2 = new QCheckBox(filterWidget_2);
        incomeCheckBox_2->setObjectName("incomeCheckBox_2");
        incomeCheckBox_2->setGeometry(QRect(10, 0, 81, 20));
        expensesCheckBox_2 = new QCheckBox(filterWidget_2);
        expensesCheckBox_2->setObjectName("expensesCheckBox_2");
        expensesCheckBox_2->setGeometry(QRect(90, 0, 81, 20));
        cardsCheckBox_2 = new QComboBox(filterWidget_2);
        cardsCheckBox_2->addItem(QString());
        cardsCheckBox_2->addItem(QString());
        cardsCheckBox_2->addItem(QString());
        cardsCheckBox_2->setObjectName("cardsCheckBox_2");
        cardsCheckBox_2->setGeometry(QRect(10, 50, 151, 22));
        label_6 = new QLabel(filterWidget_2);
        label_6->setObjectName("label_6");
        label_6->setGeometry(QRect(10, 30, 101, 16));
        main->addTab(HistoryTab_2, QString());
        DepositeTab_2 = new QWidget();
        DepositeTab_2->setObjectName("DepositeTab_2");
        CardsScroll_4 = new QScrollArea(DepositeTab_2);
        CardsScroll_4->setObjectName("CardsScroll_4");
        CardsScroll_4->setGeometry(QRect(10, 10, 361, 201));
        CardsScroll_4->setFrameShadow(QFrame::Sunken);
        CardsScroll_4->setWidgetResizable(true);
        scrollAreaWidgetContents_6 = new QWidget();
        scrollAreaWidgetContents_6->setObjectName("scrollAreaWidgetContents_6");
        scrollAreaWidgetContents_6->setGeometry(QRect(0, 0, 359, 199));
        Card_Dep1_2 = new QWidget(scrollAreaWidgetContents_6);
        Card_Dep1_2->setObjectName("Card_Dep1_2");
        Card_Dep1_2->setGeometry(QRect(0, 0, 361, 91));
        CardsScroll_4->setWidget(scrollAreaWidgetContents_6);
        main->addTab(DepositeTab_2, QString());
        OtherTab_2 = new QWidget();
        OtherTab_2->setObjectName("OtherTab_2");
        main->addTab(OtherTab_2, QString());
        msg_box = new QLabel(MainWindow);
        msg_box->setObjectName("msg_box");
        msg_box->setGeometry(QRect(630, 560, 231, 61));
        msg_box->setFont(font1);
        msg_box->setScaledContents(false);
        msg_box->setWordWrap(true);
        msg_box->setMargin(0);
        msg_box->setIndent(1);

        retranslateUi(MainWindow);

        main->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QDialog *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "MakoStream's Bank", nullptr));
        logo_main->setText(QString());
        LoginButton->setText(QCoreApplication::translate("MainWindow", "Login", nullptr));
        ForgedPasswodButton->setText(QCoreApplication::translate("MainWindow", "forgot password?", nullptr));
        login_label->setText(QCoreApplication::translate("MainWindow", "login", nullptr));
        login_line_edit->setInputMask(QString());
        login_line_edit->setText(QString());
        label->setText(QCoreApplication::translate("MainWindow", "Some project", nullptr));
        label_unput_password->setText(QCoreApplication::translate("MainWindow", "password", nullptr));
        RegisterButton->setText(QCoreApplication::translate("MainWindow", "registration", nullptr));
        label_login->setText(QCoreApplication::translate("MainWindow", "login", nullptr));
        user_id_value->setText(QCoreApplication::translate("MainWindow", "000000", nullptr));
        user_id_label->setText(QCoreApplication::translate("MainWindow", "u-id:", nullptr));
        session_id_label->setText(QCoreApplication::translate("MainWindow", "s-id:", nullptr));
        session_id_value->setText(QCoreApplication::translate("MainWindow", "000000", nullptr));
        RegisterButtonCompl->setText(QCoreApplication::translate("MainWindow", "Register", nullptr));
        logo_main_2->setText(QString());
        ProjectNameLabel->setText(QCoreApplication::translate("MainWindow", "Some project", nullptr));
        RegLabel1->setText(QCoreApplication::translate("MainWindow", "Registration", nullptr));
        NameLabel->setText(QCoreApplication::translate("MainWindow", "Name*", nullptr));
        SurnameLabel->setText(QCoreApplication::translate("MainWindow", "Surname*", nullptr));
        LoginLabel->setText(QCoreApplication::translate("MainWindow", "Login*", nullptr));
        label_2->setText(QCoreApplication::translate("MainWindow", "Password*", nullptr));
        BackToLoginButton->setText(QCoreApplication::translate("MainWindow", "Back", nullptr));
        pushButton_7->setText(QCoreApplication::translate("MainWindow", "IBAN transaction", nullptr));
        pushButton_8->setText(QCoreApplication::translate("MainWindow", "PAN transaction", nullptr));
        pushButton_9->setText(QCoreApplication::translate("MainWindow", "Other transaction", nullptr));
        user_id_value_3->setText(QCoreApplication::translate("MainWindow", "000000", nullptr));
        user_id_label_3->setText(QCoreApplication::translate("MainWindow", "u-id:", nullptr));
        session_id_value_3->setText(QCoreApplication::translate("MainWindow", "000000", nullptr));
        session_id_label_3->setText(QCoreApplication::translate("MainWindow", "s-id:", nullptr));
        Card1_image_2->setText(QString());
        Card_Value_2->setText(QCoreApplication::translate("MainWindow", "card_value", nullptr));
        Card_Value_Type_2->setText(QCoreApplication::translate("MainWindow", "err_card_value_type", nullptr));
        Card_PAN_2->setText(QCoreApplication::translate("MainWindow", "0000 0000 0000 0000", nullptr));
        Card_BankName_2->setText(QCoreApplication::translate("MainWindow", "Stream Bank", nullptr));
        Card_Name_2->setText(QCoreApplication::translate("MainWindow", "Card_Name", nullptr));
        Card_Status_2->setText(QCoreApplication::translate("MainWindow", "err_Card_Status", nullptr));
        Card_MGPM_2->setText(QCoreApplication::translate("MainWindow", "Card_Description", nullptr));
        Card_expiration_date_2->setText(QCoreApplication::translate("MainWindow", "err_Card_expiration_date", nullptr));
        Card_Iban_2->setText(QCoreApplication::translate("MainWindow", "err_Card_IBAN", nullptr));
        main->setTabText(main->indexOf(AccountsTab_2), QCoreApplication::translate("MainWindow", "Accounts", nullptr));
        IMG_logo_2->setText(QCoreApplication::translate("MainWindow", "Logo", nullptr));
        ammount_3->setText(QCoreApplication::translate("MainWindow", "err_ammount", nullptr));
        value_type_2->setText(QCoreApplication::translate("MainWindow", "err_value_type", nullptr));
        ammount_4->setText(QCoreApplication::translate("MainWindow", "err_card_lastPAN", nullptr));
        load_more_button_2->setText(QCoreApplication::translate("MainWindow", "load more...", nullptr));
        incomeCheckBox_2->setText(QCoreApplication::translate("MainWindow", "income", nullptr));
        expensesCheckBox_2->setText(QCoreApplication::translate("MainWindow", "expenses", nullptr));
        cardsCheckBox_2->setItemText(0, QCoreApplication::translate("MainWindow", "0000000000000001", nullptr));
        cardsCheckBox_2->setItemText(1, QCoreApplication::translate("MainWindow", "0000000000000002", nullptr));
        cardsCheckBox_2->setItemText(2, QCoreApplication::translate("MainWindow", "0000000000000003", nullptr));

        label_6->setText(QCoreApplication::translate("MainWindow", "Cards:", nullptr));
        main->setTabText(main->indexOf(HistoryTab_2), QCoreApplication::translate("MainWindow", "History", nullptr));
        main->setTabText(main->indexOf(DepositeTab_2), QCoreApplication::translate("MainWindow", "Deposite", nullptr));
        main->setTabText(main->indexOf(OtherTab_2), QCoreApplication::translate("MainWindow", "Other", nullptr));
        msg_box->setText(QCoreApplication::translate("MainWindow", "msg text", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_WINDOW_H
